refactor: change persisted storage constant to function to avoid execution on time of import
segmentio/analytics-next pull request #318
Opened 2021-11-07 11:27 UTC by peeyushsingla1

- We are building an application that is hosted as an iframe with in another application.
- We would like to check if cookie access is enabled and then call `await AnalyticsBrowser.load({ writeKey })` but just importing AnalyticsBrowser crashes the application.

**Steps to reproduce:-**
- `git clone https://github.com/peeyushsingla1/testing-segment-analytics`
- `yarn && yarn start`
- Block all cookies from chrome(as our application lives in iframe setting block third party cookies caused this issue).

![Screenshot 2021-11-07 at 12 16 02](https://user-images.githubusercontent.com/72206766/140642722-e30beb5d-62c4-40e1-8775-52329a0b985e.png)

- Visit application and it would break
![Screenshot 2021-11-07 at 12 09 17](https://user-images.githubusercontent.com/72206766/140642745-b6e89332-3d91-48da-ac0b-261bcf73def0.png)

**Technical Details:-**
* We would like to check if cookie access is enabled and then call `await AnalyticsBrowser.load({ writeKey })` but just importing AnalyticsBrowser crashes the application.
* Issue is happening because of [persisted](https://github.com/segmentio/analytics-next/blob/4d04b4813dd7ba539d86c31b83ccb1f96dd08d21/src/lib/priority-queue/persisted.ts#L5)

## Testing

* Its internal implementation of persisted so I guess no tests required.
* One problem after the refactoring is below test start to fail, unsure why

```
 FAIL  src/plugins/legacy-video-plugins/__tests__/index.test.ts
  ● loadLegacyVideoPlugins › attaches video plugins to ajs

    SecurityError: localStorage is not available for opaque origins
```

2021-11-08 19:29 UTC, pooyaj requested changes
@peeyushsingla1 thanks for the PR! Looks like as you pointed out a test is failing. Did you narrow down the original exception to accessing the `window.localStorage` ? What do you think of modifying the solution so we wrap the localStorage access in a `try` `catch`, and default to the stub object if localStorage is not accessible? 

Something along this line: 

```typescript
let loc:
  | Storage
  | { getItem: () => void; setItem: () => void; removeItem: () => void } = {
  getItem() {},
  setItem() {},
  removeItem() {},
}

try {
  loc = isBrowser() ? window.localStorage : loc
} catch (err) {
  console.warn('Unable to access localStorage', err)
}
```

2021-11-09 10:30 UTC, peeyushsingla1 commented
@pooyaj Good suggestion updated PR with the suggested code. tests are passing as well.

2021-11-09 17:05 UTC, pooyaj approved these changes
Looks great, thank you!

2021-11-09 17:06 UTC, merged

2021-11-09 17:16 UTC, peeyushsingla1 commented
@pooyaj thanks a lot for merging this, Wanted to ask if there would be a release with this fix soon so we can use newer version?

2021-11-09 17:34 UTC, pooyaj commented
Just published `1.31.1` 🎉