Move context augmentation to Page enrichment
segmentio/analytics-next pull request #939
Opened 2023-08-25 20:10 UTC by zikaari

Part of https://segment.atlassian.net/browse/LIBWEB-1426

Since Page Enrichment is no longer just enriching "page" events, with page information, I wanted to rename this to something generic like "Context Enrichment", but wasn't certain if this is safe. Open to discussion.

The original implementation suggests something about falling back to "options" if "context" is not there. Not sure what that means, so please help me identify what's the intended outcome of that design so I can double-check that behaviour is not impacted.

2023-08-27 02:57 UTC, silesky commented on packages/core/src/events/interfaces.ts
> +  name: string
Pretty sure every single one of these should be optional

2023-08-28 16:31 UTC, silesky requested changes

2023-08-28 16:37 UTC, silesky commented
@zikaari Definitely an improvement architecturally! 

 > I wanted to rename this to something generic like "Context Enrichment", but wasn't certain if this is safe. Open to discussion.

Cool! Yeah, I see this plugin is about augmenting the event with information from the user's environment-- so maybe EnvironmentAugmentation plugin would be a good candidate -- but "page" can also be interpreted as a kind of word for environment :-)

I mainly don't like the word 'enrichment' because this plugin isn't a type:enrichment plugin -- so it's  v confusing.

2023-08-28 23:41 UTC, zikaari commented on packages/core/src/events/interfaces.ts
> +export type Campaign = {
I copied pasted most things as-is to minimize any collateral damage, including this - but I've fixed it up now that you mentioned it

2023-08-28 23:44 UTC, zikaari commented
@pooyaj Do you know any dangers of renaming a plugin on top of your head? Not just the symbol name, but also `Plugin.name` property.

If you don't feel confident, we can leave renaming it to some other time.

2023-08-29 00:08 UTC, silesky commented on packages/browser/src/plugins/page-enrichment/index.ts
> +      version: `${getVersionType() === 'web' ? 'next' : 'npm:next'}-${version}`,
For web, this should be `next-${version}` to match the old logic?

2023-08-29 13:51 UTC, silesky approved these changes

2023-08-29 14:00 UTC, silesky commented
@zikaari change to core package (interface) should have a another changeset

2023-08-31 21:09 UTC, merged